# Generated by Django 4.0.2 on 2022-03-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Avatar', models.ImageField(upload_to='')),
                ('Name', models.CharField(default='Иван', max_length=30, verbose_name='Имя')),
                ('Surname', models.CharField(default='Иванов', max_length=40, verbose_name='Фамилия')),
                ('Patronymic', models.CharField(default='Иванович', max_length=40, verbose_name='Отчество')),
                ('UserName', models.CharField(max_length=60, verbose_name='Имя пользователя')),
                ('Password', models.CharField(max_length=20, verbose_name='Пароль')),
                ('New_password', models.CharField(max_length=20, verbose_name='Новый пароль')),
                ('Repeat_the_password', models.CharField(max_length=20, verbose_name='Повторите пароль')),
                ('Date_of_birth', models.DateField(verbose_name='Дата рождения')),
            ],
        ),
    ]
