# Generated by Django 4.0.2 on 2022-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_rename_user_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/img', verbose_name='Пользовательское фото'),
        ),
    ]
