# Generated by Django 4.0.2 on 2022-02-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_articles_options_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Название'),
        ),
    ]
