# Generated by Django 4.0.2 on 2022-05-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_articles_author_alter_articles_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comments',
            field=models.CharField(max_length=150, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='articles',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Колличество лайков'),
        ),
    ]
